config/routes.rb
Rails.application.routes.draw do

  # Home
  root to: 'home#index'
  get 'time', to: 'home#time'

  # Days & Meals
  get 'today', to: 'days#today'
  get 'date', to: 'days#date'
  resources :days do
    resources :meals, shallow: true
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  has_many :meals, -> { order(:minutes_since_midnight) }, dependent: :destroy

  def day_string
    date.strftime("%A %b %d, %Y") if date
  end

  def yesterday
    date-1
  end

  def tomorrow
    date+1
  end

  def totals
    tot = Array.new(7, 0)
    meals.each do |m|
      m.categories.each_with_index do |c, i|
        tot[i] = tot[i].to_f + c.to_f
      end
    end
    tot
  end

  def targets
    targ = Array.new(7, 0)
    targ[0] = 4
    targ[1] = 3
    targ[2] = 4
    targ[3] = 3
    targ[4] = 1
    targ[5] = 1
    targ[6] = 3
    targ
  end

  def remainders
    tot = totals
    targ = targets
    rem = Array.new(7, 0)
    tot.each do |i|
      rem[i] = targ[i] - tot[i]
    end
    rem
  end

end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :day

  def time_of_day
    Time.new.at_midnight.advance(minutes: minutes_since_midnight || 0)
  end

  def time_of_day=(val)
    self.minutes_since_midnight = ((val - Time.new.at_midnight) / 60).floor
  end

  def time_string
    time_of_day.strftime("%I:%M%p")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  # GET /days
  # GET /days.json
  def index
    @days = Day.order(:date).all
  end

  # GET /today
  def today
  end

  # GET /date
  # GET /date.json
  def date
    puts params[:date]
    @day = Day.where(date: params[:date]).first # find today by date passed in from JS
    puts @day.inspect
    if !@day
      @day = Day.new(date: params[:date]) # create today
      @day.save()
      puts @day.inspect
    end

    respond_to do |format|
      format.html { redirect_to @day }
      format.json { render :show, status: :created, location: @day }
    end
    
  end

  # GET /days/1
  # GET /days/1.json
  def show
    puts @day.inspect
  end

  # GET /days/new
  def new
    @day = Day.new
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to @day, notice: 'Day was successfully created.' }
        format.json { render :show, status: :created, location: @day }
      else
        format.html { render :new }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to @day, notice: 'Day was successfully updated.' }
        format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url, notice: 'Day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :plan, :fitness, :notes)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  # GET /time.json
  def time
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_day, only: [:index, :new, :create]
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /days/:day_id/meals/1
  # GET /days/:day_id/meals/1.json
  def index
    @meals = @day.meals.order(:minutes_since_midnight).all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
  end

  # GET /days/:day_id/meals/new
  def new
    @meal = Meal.new
    Time.zone = 'Pacific Time (US & Canada)'
    @meal.time_of_day = Time.zone.now
    puts @meal.time_of_day
    puts @meal.time_of_day.zone
  end

  # GET /meals/1/edit
  def edit
    @day = @meal.day
  end

  # POST /days/:day_id/meals
  # POST /days/:day_id/meals.json
  def create
    @meal = @day.meals.create(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal.day, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      puts params.inspect
      puts params[:meal].inspect
      puts "** meals#update time_of_day=#{params[:meal][:time_of_day]}"
      @meal.time_of_day = params[:meal][:time_of_day]
      if @meal.update(meal_params)
        format.html { redirect_to @meal.day, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    day = @meal.day
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to day_url(day), notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:day_id])
      puts @day.inspect
    end

    def set_meal
      @meal = Meal.find(params[:id])
      puts @meal.inspect
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:minutes_since_midnight, :foods, :categories => [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/days/_form.html.erb
<%= form_with(model: day, local: true) do |form| %>
  <% if day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :plan %>
    <%= form.text_field :plan %>
  </div>

  <div class="field">
    <%= form.label :fitness %>
    <%= form.text_field :fitness %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing Day</h1>

<%= render 'form', day: @day %>

<%= link_to '<< Back', @day %>

app/views/days/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Days</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Plan</th>
      <th>Fitness</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @days.each do |day| %>
      <tr>
        <td><%= link_to day.day_string, day %></td>
        <td><%= day.plan %></td>
        <td><%= day.fitness %></td>
        <td><%= day.notes %></td>
        <td><%= button_to 'Edit', edit_day_path(day), options = { method: :get } %></td>
        <td><%= button_to 'X', day, options = { method: :delete, data: { confirm: 'Are you sure?' } } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New Day</h1>

<%= render 'form', day: @day %>

<%= link_to '<< Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= link_to '<<', date_path(:date => @day.yesterday) %>
  <%= @day.day_string %>
  <%= link_to '>>', date_path(:date => @day.tomorrow) %>
</h2>

<p>
  <strong>Plan:</strong>
  <%= @day.plan %>
</p>

<p>
  <strong>Fitness:</strong>
  <%= @day.fitness %>
</p>

<p>
  <strong>Meals:</strong>
</p>

<table>
  <thead>
    <tr>
      <th class="time">Time</th>
      <th class="category veggies">Veggies</th>
      <th class="category fruits">Fruits</th>
      <th class="category proteins">Proteins</th>
      <th class="category carbs">Carbs</th>
      <th class="category fats">Fats</th>
      <th class="category seeds">Seeds</th>
      <th class="category oils">Oils</th>
      <th class="foods">Foods</th>
    </tr>
  </thead>

  <tbody>
    <%= render @day.meals %>
    <td class="time total">TOTALS</td>
    <td class="category veggies total"><%= @day.totals[0] %></td>
    <td class="category fruits total"><%= @day.totals[1] %></td>
    <td class="category proteins total"><%= @day.totals[2] %></td>
    <td class="category carbs total"><%= @day.totals[3] %></td>
    <td class="category fats total"><%= @day.totals[4] %></td>
    <td class="category seeds total"><%= @day.totals[5] %></td>
    <td class="category oils total"><%= @day.totals[6] %></td>
    <td class="foods"></td>
  </tbody>
</table>

<%= link_to 'New Meal', new_day_meal_path(@day) %>

<p>
  <strong>Notes:</strong>
  <%= @day.notes %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to '<< Back', days_path %>

app/views/days/today.html.erb
<script>
  console.log("fetching Today")
  var date = new Date(Date.now())
  console.log(date)
  var dateString = `${date.getFullYear()}/${date.getMonth()+1}/${date.getDate()}` // Months are 0-11
  console.log(dateString)
  fetch('/date.json?date='+dateString)
  window.location.replace('/date?date='+dateString);
</script>

app/views/home/index.html.erb
<head>
  <%= javascript_pack_tag 'vue' %>
  <%= stylesheet_pack_tag 'vue' %>
</head>

<div id='app'>
  <App />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('diet.ico'), :rel => 'icon', :type =>  'image/x-icon' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>

    <%= yield %>

    <%= debug(params) if Rails.env.development? %>

  </body>

</html>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal, url: @meal.new_record? ? day_meals_path : @meal) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2><%= @day.day_string %></h2>

  <table>
    <thead>
      <tr>
        <td class="time"><strong><%= form.label "Time (minutes since midnight)" %></strong></td>
        <td class="category veggies"><strong><%= form.label "Veggies" %></strong></td>
        <td class="category fruits"><strong><%= form.label "Fruits" %></strong></td>
        <td class="category proteins"><strong><%= form.label "Proteins" %></strong></td>
        <td class="category carbs"><strong><%= form.label "Carbs" %></strong></td>
        <td class="category fats"><strong><%= form.label "Fats" %></strong></td>
        <td class="category seeds"><strong><%= form.label "Seeds" %></strong></td>
        <td class="category oils"><strong><%= form.label "Oils" %></strong></td>
        <td class="foods"><strong><%= form.label :foods %></strong></td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="time"><%= form.input_field :minutes_since_midnight %> = <%= @meal.time_string  %></td>
        <%= form.input_field :categories, as: :array %>
        <td class="foods"><%= form.text_field :foods %></td>
        <td><%= form.submit %></td>
      </tr>
    </tbody>
  </table>

<% end %>

app/views/meals/_meal.html.erb
<tr>
  <td class="time"><%= meal.time_string %></td>
  <td class="category veggies"><%= meal.categories[0] %></td>
  <td class="category fruits"><%= meal.categories[1] %></td>
  <td class="category proteins"><%= meal.categories[2] %></td>
  <td class="category carbs"><%= meal.categories[3] %></td>
  <td class="category fats"><%= meal.categories[4] %></td>
  <td class="category seeds"><%= meal.categories[5] %></td>
  <td class="category oils"><%= meal.categories[6] %></td>
  <td class="foods"><%= meal.foods %></td>
  <td><%= button_to 'Edit', edit_meal_path(meal), options = { method: :get } %></td>
  <td><%= button_to 'X', meal, options = { method: :delete, data: { confirm: 'Are you sure?' } } %></td>
</tr>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to '<< Back', @meal.day %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form', day: @day, meal: @meal %>

<%= link_to '<< Back', @day %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @meal.day.day_string %></h2>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Foods</th>
      <th>Veggies</th>
      <th>Fruits</th>
      <th>Proteins</th>
      <th>Carbs</th>
      <th>Fats</th>
      <th>Seeds</th>
      <th>Oils</th>
    </tr>
  </thead>

  <tbody>
    <%= render @meal %>
  </tbody>
</table>

<%= link_to '<< Back', @meal.day %>